/**
 * Minimal hand-rolled replacement for Manus's platform-managed `_core` context.
 * The original project export references `./_core/context` throughout (routers.ts,
 * both test files) but the actual module was not included in the export — it's
 * generated by the Manus platform, not user-authored source. This reconstructs
 * just the shape the app and its tests actually need.
 *
 * Nothing in `legacy.*` (the real AgeCare functionality) reads `ctx.user` — every
 * legacy procedure takes an explicit `token` input and forwards it to the legacy
 * REST API. `ctx.user` only backs the vestigial `auth.me`/`auth.logout`
 * procedures, which were part of Manus's own OAuth scaffold and are not wired
 * into the AgeCare UI (Home.tsx authenticates via `legacy.login`/`legacy.register`
 * and stores the returned JWT itself). `user` is always `null` here since no
 * OAuth login flow is implemented in this reconstruction.
 */
import type { Request, Response } from "express";

export type AuthenticatedUser = {
  id: number;
  openId: string;
  email: string | null;
  name: string | null;
  loginMethod: string | null;
  role: string;
  createdAt: Date;
  updatedAt: Date;
  lastSignedIn: Date | null;
};

export type TrpcContext = {
  user: AuthenticatedUser | null;
  req: Request;
  res: Response;
};
