const statements = [
  `CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'patient' CHECK (role IN ('patient', 'caregiver')),
    phone TEXT,
    date_of_birth DATE,
    reset_token TEXT,
    reset_expires BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci_idx ON users (LOWER(email))`,
  `CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mood SMALLINT CHECK (mood BETWEEN 1 AND 5),
    energy SMALLINT CHECK (energy BETWEEN 1 AND 5),
    pain SMALLINT CHECK (pain BETWEEN 0 AND 10),
    sleep_hours NUMERIC,
    notes TEXT,
    ai_response TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    dosage TEXT,
    frequency TEXT,
    time_of_day TEXT,
    start_date DATE,
    end_date DATE,
    notes TEXT,
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    doctor_name TEXT NOT NULL,
    specialty TEXT,
    location TEXT,
    appointment_date TIMESTAMPTZ NOT NULL,
    notes TEXT,
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS vital_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blood_pressure_sys SMALLINT,
    blood_pressure_dia SMALLINT,
    heart_rate SMALLINT,
    temperature NUMERIC,
    weight NUMERIC,
    blood_sugar SMALLINT,
    spo2 SMALLINT,
    notes TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS family_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    relationship TEXT,
    phone TEXT,
    email TEXT,
    notify_email SMALLINT NOT NULL DEFAULT 1,
    notify_sms SMALLINT NOT NULL DEFAULT 0,
    is_active SMALLINT NOT NULL DEFAULT 1,
    linked_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS care_access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    caregiver_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    relationship TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'denied', 'revoked', 'expired')),
    requested_scopes TEXT NOT NULL DEFAULT '["checkins:read"]',
    granted_scopes TEXT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (patient_user_id, caregiver_user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS care_access_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT REFERENCES care_access_grants(id) ON DELETE SET NULL,
    actor_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    patient_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    scope TEXT,
    outcome TEXT NOT NULL CHECK (outcome IN ('allowed', 'denied', 'changed')),
    record_count INTEGER,
    request_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    model TEXT,
    tokens_used INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  // Repairs a database created before this fix. CREATE TABLE IF NOT EXISTS
  // above is a no-op on an already-existing table, so if a previous version
  // of this table lacks a `tokens_used` column under whatever name it had
  // before (the first attempt at this fix assumed it was `token_count` and
  // used a rename -- rather than trust that assumption a second time,
  // unconditionally ensuring the column exists is correct regardless of
  // what, if anything, it used to be called). Every chat message was
  // failing with a Postgres "column does not exist" error, reported to
  // users as a generic "Chat failed." ADD COLUMN IF NOT EXISTS is a no-op
  // on a fresh table (already has it from the CREATE TABLE above) or one
  // already repaired.
  `ALTER TABLE chat_history ADD COLUMN IF NOT EXISTS tokens_used INTEGER`,
  `CREATE TABLE IF NOT EXISTS notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES family_contacts(id) ON DELETE CASCADE,
    checkin_id BIGINT REFERENCES checkins(id) ON DELETE SET NULL,
    type TEXT NOT NULL CHECK (type IN ('email', 'sms')),
    status TEXT NOT NULL DEFAULT 'pending',
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_checkins_user ON checkins(user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_medications_user ON medications(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_appointments_user ON appointments(user_id, appointment_date)`,
  `CREATE INDEX IF NOT EXISTS idx_vitals_user ON vital_signs(user_id, recorded_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_family_active ON family_contacts(user_id, is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_family_linked ON family_contacts(linked_user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_care_access_patient ON care_access_grants(patient_user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_care_access_caregiver ON care_access_grants(caregiver_user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_care_access_audit_patient ON care_access_audit(patient_user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_notification_log_status ON notification_log(status, created_at)`,
];

async function runPostgresSchema(pool) {
  for (const statement of statements) await pool.query(statement);
}

module.exports = { statements, runPostgresSchema };
