const statements = [
  `CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    name TEXT,
    full_name TEXT,
    role TEXT NOT NULL DEFAULT 'patient' CHECK (role IN ('patient', 'caregiver')),
    phone TEXT,
    date_of_birth DATE,
    reset_token TEXT,
    reset_expires BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS users_email_ci_idx ON users (LOWER(email))`,
  `CREATE TABLE IF NOT EXISTS checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mood SMALLINT CHECK (mood BETWEEN 1 AND 5),
    energy SMALLINT CHECK (energy BETWEEN 1 AND 5),
    pain SMALLINT CHECK (pain BETWEEN 0 AND 10),
    sleep_hours NUMERIC,
    notes TEXT,
    ai_response TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    dosage TEXT,
    frequency TEXT,
    time_of_day TEXT,
    start_date DATE,
    end_date DATE,
    notes TEXT,
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    doctor_name TEXT NOT NULL,
    specialty TEXT,
    location TEXT,
    appointment_date TIMESTAMPTZ NOT NULL,
    notes TEXT,
    is_active SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS vital_signs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    blood_pressure_sys SMALLINT,
    blood_pressure_dia SMALLINT,
    heart_rate SMALLINT,
    temperature NUMERIC,
    weight NUMERIC,
    blood_sugar SMALLINT,
    spo2 SMALLINT,
    notes TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS family_contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    relationship TEXT,
    phone TEXT,
    email TEXT,
    notify_email SMALLINT NOT NULL DEFAULT 1,
    notify_sms SMALLINT NOT NULL DEFAULT 0,
    is_active SMALLINT NOT NULL DEFAULT 1,
    linked_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS care_access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    caregiver_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    relationship TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'active', 'denied', 'revoked', 'expired')),
    requested_scopes TEXT NOT NULL DEFAULT '["checkins:read"]',
    granted_scopes TEXT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (patient_user_id, caregiver_user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS care_access_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT REFERENCES care_access_grants(id) ON DELETE SET NULL,
    actor_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    patient_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    scope TEXT,
    outcome TEXT NOT NULL CHECK (outcome IN ('allowed', 'denied', 'changed')),
    record_count INTEGER,
    request_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    model TEXT,
    tokens_used INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  // Repairs a database created before this fix. CREATE TABLE IF NOT EXISTS
  // above is a no-op on an already-existing table, so if a previous version
  // of this table lacks a `tokens_used` column under whatever name it had
  // before (the first attempt at this fix assumed it was `token_count` and
  // used a rename -- rather than trust that assumption a second time,
  // unconditionally ensuring the column exists is correct regardless of
  // what, if anything, it used to be called). Every chat message was
  // failing with a Postgres "column does not exist" error, reported to
  // users as a generic "Chat failed." ADD COLUMN IF NOT EXISTS is a no-op
  // on a fresh table (already has it from the CREATE TABLE above) or one
  // already repaired.
  `ALTER TABLE chat_history ADD COLUMN IF NOT EXISTS tokens_used INTEGER`,
  `CREATE TABLE IF NOT EXISTS notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES family_contacts(id) ON DELETE CASCADE,
    checkin_id BIGINT REFERENCES checkins(id) ON DELETE SET NULL,
    type TEXT NOT NULL CHECK (type IN ('email', 'sms')),
    status TEXT NOT NULL DEFAULT 'pending',
    retry_count INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  // Reminder preferences, one row of settings per user. Unconditional ADD
  // COLUMN IF NOT EXISTS (rather than trusting a plain CREATE TABLE, which
  // is a no-op against an already-existing users table) -- same reasoning
  // as the tokens_used repair above: this table always already exists in
  // production by the time this ships.
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'Australia/Sydney'`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS checkin_reminder_time TEXT NOT NULL DEFAULT '09:00'`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS checkin_reminder_enabled SMALLINT NOT NULL DEFAULT 1`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS medication_reminders_enabled SMALLINT NOT NULL DEFAULT 1`,
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS appointment_reminders_enabled SMALLINT NOT NULL DEFAULT 1`,
  // Defaults to 0 (opt-in) -- see migrations/notifications.js for why this one doesn't
  // default to on like the other reminder toggles.
  `ALTER TABLE users ADD COLUMN IF NOT EXISTS missed_checkin_alerts_enabled SMALLINT NOT NULL DEFAULT 0`,
  `CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions(user_id)`,
  // reference_id defaults to 0, not NULL -- Postgres (like SQLite) treats
  // every NULL as distinct under a UNIQUE constraint, which would let the
  // check-in reminder (no medication to reference) bypass the dedupe this
  // table exists for.
  //
  // reminder_type deliberately has NO CHECK constraint restricting its
  // values (a previous version did, listing only 'checkin', 'medication',
  // 'medication_renewal' -- see the DROP CONSTRAINT repair immediately
  // below). reminder_type is purely an internal application-level tag with
  // no other table referencing it, and the set of reminder types has
  // already grown twice since ('appointment', 'missed_checkin_family_alert')
  // with more (vital-sign alerts) planned -- a fixed enum here is the wrong
  // tool and is exactly what caused a real bug: every appointment reminder
  // and missed-check-in alert failed its claimReminder INSERT with a CHECK
  // violation on every single tick from the moment those features shipped,
  // silently, because claimReminder's error handling only recognizes UNIQUE
  // violations as "already claimed" and treats anything else (including
  // this) as a hard failure logged once per tick and otherwise swallowed.
  // SQLite's copy of this table (migrations/notifications.js) never had
  // this constraint, which is why SQLite-based tests and local smoke
  // testing never caught it -- only real Postgres did.
  `CREATE TABLE IF NOT EXISTS reminder_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reminder_type TEXT NOT NULL,
    reference_id BIGINT NOT NULL DEFAULT 0,
    reminder_date DATE NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, reminder_type, reference_id, reminder_date)
  )`,
  // Repairs a database created before this fix. This does NOT guess the
  // constraint's auto-generated name (confirmed empirically that different
  // Postgres-family engines name an unnamed single-column CHECK constraint
  // differently -- pg-mem, used by this repo's tests, does not match real
  // Postgres's own "{table}_{column}_check" convention, so a name guessed
  // from one isn't safe to trust against the other, and this needs to work
  // against whichever real Postgres actually named it). Instead it looks up
  // any CHECK constraint on reminder_log whose definition mentions
  // 'medication_renewal' -- a fingerprint that only the old restrictive
  // constraint's value list contains -- and drops it by its real name,
  // whatever that turns out to be. A DO block is the only way to do that
  // dynamically in plain SQL; runPostgresSchema (below) tolerates any
  // single statement failing (logging it) rather than crashing the whole
  // migration, since pg-mem itself can't execute plpgsql at all and would
  // otherwise fail this exact statement in every test run.
  `DO $do$
   DECLARE
     old_constraint_name text;
   BEGIN
     SELECT con.conname INTO old_constraint_name
     FROM pg_constraint con
     JOIN pg_class rel ON rel.oid = con.conrelid
     WHERE rel.relname = 'reminder_log'
       AND con.contype = 'c'
       AND pg_get_constraintdef(con.oid) ILIKE '%medication_renewal%';
     IF old_constraint_name IS NOT NULL THEN
       EXECUTE format('ALTER TABLE reminder_log DROP CONSTRAINT %I', old_constraint_name);
     END IF;
   END
   $do$;`,
  `CREATE INDEX IF NOT EXISTS idx_reminder_log_lookup ON reminder_log(user_id, reminder_type, reminder_date)`,
  `CREATE INDEX IF NOT EXISTS idx_checkins_user ON checkins(user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_medications_user ON medications(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_appointments_user ON appointments(user_id, appointment_date)`,
  `CREATE INDEX IF NOT EXISTS idx_vitals_user ON vital_signs(user_id, recorded_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_family_active ON family_contacts(user_id, is_active)`,
  `CREATE INDEX IF NOT EXISTS idx_family_linked ON family_contacts(linked_user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_care_access_patient ON care_access_grants(patient_user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_care_access_caregiver ON care_access_grants(caregiver_user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_care_access_audit_patient ON care_access_audit(patient_user_id, created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_notification_log_status ON notification_log(status, created_at)`,
];

async function runPostgresSchema(pool) {
  // Tolerant per-statement, matching how server.js's SQLite runMigration
  // already treats each migration statement independently (log and move
  // on) rather than letting one failure abort everything after it -- an
  // early statement failing used to be able to prevent totally unrelated
  // tables/columns later in this same list from ever being created.
  for (const statement of statements) {
    try {
      await pool.query(statement);
    } catch (error) {
      console.error(`[Migration] PostgreSQL statement failed (continuing): ${error.message}`);
      console.error(`[Migration]   statement: ${statement.trim().replace(/\s+/g, ' ').slice(0, 160)}...`);
    }
  }
}

module.exports = { statements, runPostgresSchema };
