import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Language = "en" | "ar" | "es" | "zh" | "vi";

export const supportedLanguages: readonly Language[] = ["en", "ar", "es", "zh", "vi"];

export function resolveInitialLanguage(search: string, stored: string | null): Language {
  const requested = new URLSearchParams(search).get("lang");
  if (supportedLanguages.includes(requested as Language)) return requested as Language;
  return supportedLanguages.includes(stored as Language) ? stored as Language : "en";
}

type TranslationKey = keyof typeof translations.en;

const translations = {
  en: {
    language: "Language",
    english: "English",
    arabic: "Arabic",
    spanish: "Spanish",
    chinese: "Chinese",
    vietnamese: "Vietnamese",
    today: "Today",
    myCare: "My care",
    together: "Together",
    dayAtAGlance: "Day at a glance",
    dailyCheckin: "Daily check-in",
    medications: "Medications",
    appointments: "Appointments",
    vitalSigns: "Vital signs",
    careChat: "Care chat",
    familyCircle: "Family circle",
    linkPatient: "Link a patient",
    careConnections: "Care Connections",
    careHistory: "Care history",
    primaryNavigation: "Primary navigation",
    dailyCompanion: "Your daily companion",
    yourCareSpace: "Your care space",
    connected: "AgeCare connected",
    privateAndPersonal: "Private and personal",
    accountConnection: "Account connection",
    connectAgeCare: "Connect AgeCare",
    disconnect: "Disconnect",
    signIn: "Sign in",
    createAccount: "Create account",
    existingAccount: "Existing account",
    newAccount: "New account",
    connectTitle: "Connect to AgeCare.",
    registerTitle: "Create your AgeCare account.",
    signInCopy: "Use the email and password from your original AgeCare app. We use this only to load your own services.",
    registerCopy: "Create an account to begin keeping your own private care records.",
    fullName: "Full name",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm password",
    connectMyAccount: "Connect my account",
    creatingAccount: "Creating account",
    connecting: "Connecting",
    alreadyHaveAccount: "Already have an account? Sign in",
    newToAgeCare: "New to AgeCare? Create an account",
    passwordTooShort: "Use a password with at least 6 characters.",
    passwordsDoNotMatch: "The passwords do not match.",
    closeAccountAccess: "Close account access",
  },
  ar: {
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    spanish: "Español",
    chinese: "中文",
    vietnamese: "Tiếng Việt",
    today: "اليوم",
    myCare: "رعايتي",
    together: "معاً",
    dayAtAGlance: "نظرة على اليوم",
    dailyCheckin: "متابعة يومية",
    medications: "الأدوية",
    appointments: "المواعيد",
    vitalSigns: "العلامات الحيوية",
    careChat: "محادثة الرعاية",
    familyCircle: "دائرة العائلة",
    linkPatient: "ربط مريض",
    careConnections: "روابط الرعاية",
    careHistory: "سجل الرعاية",
    primaryNavigation: "التنقل الرئيسي",
    dailyCompanion: "رفيقك اليومي",
    yourCareSpace: "مساحة رعايتك",
    connected: "تم الاتصال بـ AgeCare",
    privateAndPersonal: "خاص وشخصي",
    accountConnection: "اتصال الحساب",
    connectAgeCare: "الاتصال بـ AgeCare",
    disconnect: "قطع الاتصال",
    signIn: "تسجيل الدخول",
    createAccount: "إنشاء حساب",
    existingAccount: "حساب موجود",
    newAccount: "حساب جديد",
    connectTitle: "الاتصال بـ AgeCare.",
    registerTitle: "أنشئ حساب AgeCare الخاص بك.",
    signInCopy: "استخدم البريد الإلكتروني وكلمة المرور من تطبيق AgeCare الأصلي. نستخدمهما فقط لتحميل خدماتك الخاصة.",
    registerCopy: "أنشئ حساباً لبدء الاحتفاظ بسجلات رعايتك الخاصة.",
    fullName: "الاسم الكامل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    connectMyAccount: "اتصال بحسابي",
    creatingAccount: "جارٍ إنشاء الحساب",
    connecting: "جارٍ الاتصال",
    alreadyHaveAccount: "لديك حساب بالفعل؟ سجّل الدخول",
    newToAgeCare: "جديد في AgeCare؟ أنشئ حساباً",
    passwordTooShort: "استخدم كلمة مرور من 6 أحرف على الأقل.",
    passwordsDoNotMatch: "كلمتا المرور غير متطابقتين.",
    closeAccountAccess: "إغلاق الوصول إلى الحساب",
  },
  es: {
    language: "Idioma",
    english: "English",
    arabic: "العربية",
    spanish: "Español",
    chinese: "中文",
    vietnamese: "Tiếng Việt",
    today: "Hoy",
    myCare: "Mi cuidado",
    together: "Juntos",
    dayAtAGlance: "Resumen del día",
    dailyCheckin: "Registro diario",
    medications: "Medicamentos",
    appointments: "Citas",
    vitalSigns: "Signos vitales",
    careChat: "Chat de cuidado",
    familyCircle: "Círculo familiar",
    linkPatient: "Vincular a un paciente",
    careConnections: "Conexiones de cuidado",
    careHistory: "Historial de cuidado",
    primaryNavigation: "Navegación principal",
    dailyCompanion: "Tu acompañante diario",
    yourCareSpace: "Tu espacio de cuidado",
    connected: "AgeCare conectado",
    privateAndPersonal: "Privado y personal",
    accountConnection: "Conexión de cuenta",
    connectAgeCare: "Conectar AgeCare",
    disconnect: "Desconectar",
    signIn: "Iniciar sesión",
    createAccount: "Crear cuenta",
    existingAccount: "Cuenta existente",
    newAccount: "Cuenta nueva",
    connectTitle: "Conéctate a AgeCare.",
    registerTitle: "Crea tu cuenta de AgeCare.",
    signInCopy: "Usa el correo y la contraseña de tu aplicación AgeCare original. Solo los usamos para cargar tus propios servicios.",
    registerCopy: "Crea una cuenta para comenzar a guardar tus propios registros privados de cuidado.",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    connectMyAccount: "Conectar mi cuenta",
    creatingAccount: "Creando cuenta",
    connecting: "Conectando",
    alreadyHaveAccount: "¿Ya tienes una cuenta? Inicia sesión",
    newToAgeCare: "¿Eres nuevo en AgeCare? Crea una cuenta",
    passwordTooShort: "Usa una contraseña de al menos 6 caracteres.",
    passwordsDoNotMatch: "Las contraseñas no coinciden.",
    closeAccountAccess: "Cerrar acceso a la cuenta",
  },
  zh: {
    language: "语言",
    english: "English",
    arabic: "العربية",
    spanish: "Español",
    chinese: "中文",
    vietnamese: "Tiếng Việt",
    today: "今天",
    myCare: "我的护理",
    together: "共同关怀",
    dayAtAGlance: "今日概览",
    dailyCheckin: "每日签到",
    medications: "药物",
    appointments: "预约",
    vitalSigns: "生命体征",
    careChat: "护理对话",
    familyCircle: "家庭圈",
    linkPatient: "关联患者",
    careConnections: "护理联系",
    careHistory: "护理记录",
    primaryNavigation: "主导航",
    dailyCompanion: "您的每日伙伴",
    yourCareSpace: "您的护理空间",
    connected: "已连接 AgeCare",
    privateAndPersonal: "私密且个人化",
    accountConnection: "账户连接",
    connectAgeCare: "连接 AgeCare",
    disconnect: "断开连接",
    signIn: "登录",
    createAccount: "创建账户",
    existingAccount: "已有账户",
    newAccount: "新账户",
    connectTitle: "连接到 AgeCare。",
    registerTitle: "创建您的 AgeCare 账户。",
    signInCopy: "请使用您原 AgeCare 应用的电子邮箱和密码。我们仅用它来加载您自己的服务。",
    registerCopy: "创建账户,开始保存您自己的私人护理记录。",
    fullName: "姓名",
    email: "电子邮箱",
    password: "密码",
    confirmPassword: "确认密码",
    connectMyAccount: "连接我的账户",
    creatingAccount: "正在创建账户",
    connecting: "正在连接",
    alreadyHaveAccount: "已有账户？登录",
    newToAgeCare: "初次使用 AgeCare？创建账户",
    passwordTooShort: "密码至少需要 6 个字符。",
    passwordsDoNotMatch: "两次输入的密码不一致。",
    closeAccountAccess: "关闭账户访问",
  },
  vi: {
    language: "Ngôn ngữ",
    english: "English",
    arabic: "العربية",
    spanish: "Español",
    chinese: "中文",
    vietnamese: "Tiếng Việt",
    today: "Hôm nay",
    myCare: "Chăm sóc của tôi",
    together: "Cùng nhau",
    dayAtAGlance: "Tổng quan trong ngày",
    dailyCheckin: "Điểm danh hằng ngày",
    medications: "Thuốc",
    appointments: "Lịch hẹn",
    vitalSigns: "Dấu hiệu sinh tồn",
    careChat: "Trò chuyện chăm sóc",
    familyCircle: "Vòng tròn gia đình",
    linkPatient: "Liên kết bệnh nhân",
    careConnections: "Kết nối chăm sóc",
    careHistory: "Lịch sử chăm sóc",
    primaryNavigation: "Điều hướng chính",
    dailyCompanion: "Người bạn đồng hành hằng ngày của bạn",
    yourCareSpace: "Không gian chăm sóc của bạn",
    connected: "Đã kết nối AgeCare",
    privateAndPersonal: "Riêng tư và cá nhân",
    accountConnection: "Kết nối tài khoản",
    connectAgeCare: "Kết nối AgeCare",
    disconnect: "Ngắt kết nối",
    signIn: "Đăng nhập",
    createAccount: "Tạo tài khoản",
    existingAccount: "Tài khoản hiện có",
    newAccount: "Tài khoản mới",
    connectTitle: "Kết nối với AgeCare.",
    registerTitle: "Tạo tài khoản AgeCare của bạn.",
    signInCopy: "Sử dụng email và mật khẩu từ ứng dụng AgeCare gốc của bạn. Chúng tôi chỉ dùng thông tin này để tải các dịch vụ của riêng bạn.",
    registerCopy: "Tạo tài khoản để bắt đầu lưu giữ hồ sơ chăm sóc riêng tư của bạn.",
    fullName: "Họ và tên",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Xác nhận mật khẩu",
    connectMyAccount: "Kết nối tài khoản của tôi",
    creatingAccount: "Đang tạo tài khoản",
    connecting: "Đang kết nối",
    alreadyHaveAccount: "Đã có tài khoản? Đăng nhập",
    newToAgeCare: "Mới sử dụng AgeCare? Tạo tài khoản",
    passwordTooShort: "Sử dụng mật khẩu có ít nhất 6 ký tự.",
    passwordsDoNotMatch: "Mật khẩu không khớp.",
    closeAccountAccess: "Đóng quyền truy cập tài khoản",
  },
} as const;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  direction: "ltr" | "rtl";
  t: (key: TranslationKey) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window === "undefined") return "en";
    return resolveInitialLanguage(window.location.search, window.localStorage.getItem("agecare-language"));
  });
  const direction: "ltr" | "rtl" = language === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    if (typeof window === "undefined") return;
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
    window.localStorage.setItem("agecare-language", language);
  }, [direction, language]);

  const value = useMemo(() => ({ language, setLanguage, direction, t: (key: TranslationKey) => translations[language][key] }), [direction, language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
