/**
 * Live-service panels for the existing AgeCare account.
 * These panels render only data returned from the configured legacy API and restore the original service operations.
 */
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/contexts/LanguageContext";
import { getRegistrationValidationError } from "@/lib/accountValidation";
import { Activity, CalendarDays, Check, ClipboardCheck, HeartHandshake, Link2, LoaderCircle, MessageCircle, Pencil, Plus, Send, Trash2, UsersRound, X } from "lucide-react";
import React, { useState, type FormEvent, type ReactNode } from "react";

type CheckinPayload = { mood: number; energy: number; pain: number; sleepHours?: number; notes?: string };
type RecordShape = Record<string, unknown>;
export type EditableResource = "medications" | "appointments" | "vitals";
export type ChatMessage = { role: "user" | "assistant"; content: string };

type ResourceField = { key: string; label: string; type?: "text" | "number" | "date" | "datetime-local"; required?: boolean; step?: string; options?: string[] };
type ResourceConfig = { title: string; eyebrow: string; description: string; emptyTitle: string; emptyCopy: string; fields: ResourceField[]; getTitle: (record: RecordShape) => string; getDetail: (record: RecordShape) => string };

const resources: Record<EditableResource, ResourceConfig> = {
  medications: { title: "Medication routines", eyebrow: "My care", description: "Medication records from your existing AgeCare account.", emptyTitle: "No medications have been added yet.", emptyCopy: "Add the medicine you take and choose a reminder routine.", fields: [{ key: "name", label: "Medication name", required: true }, { key: "dosage", label: "Dosage", required: true }, { key: "frequency", label: "Frequency" }, { key: "time_of_day", label: "Time of day", options: ["Morning", "Afternoon", "Evening", "Bedtime"] }, { key: "start_date", label: "Start date", type: "date" }, { key: "end_date", label: "End date", type: "date" }, { key: "notes", label: "Notes" }], getTitle: (record) => String(record.name ?? "Medication"), getDetail: (record) => [record.dosage, record.frequency, record.time_of_day].filter(Boolean).join(" · ") || "No reminder detail" },
  appointments: { title: "Appointments", eyebrow: "Looking ahead", description: "Scheduled care appointments from your existing AgeCare account.", emptyTitle: "No appointments are scheduled yet.", emptyCopy: "Add the next appointment to keep it close to your care routine.", fields: [{ key: "doctor_name", label: "Doctor or provider", required: true }, { key: "specialty", label: "Specialty" }, { key: "location", label: "Location" }, { key: "appointment_date", label: "Date and time", type: "datetime-local", required: true }, { key: "notes", label: "Notes" }], getTitle: (record) => String(record.doctor_name ?? "Appointment"), getDetail: (record) => [record.specialty, record.appointment_date && new Date(String(record.appointment_date)).toLocaleString(), record.location].filter(Boolean).join(" · ") || "No appointment detail" },
  vitals: { title: "Vital signs", eyebrow: "A clear record", description: "Vital-sign readings from your existing AgeCare account.", emptyTitle: "No vital-sign readings have been recorded yet.", emptyCopy: "Record a reading to build a clearer picture over time.", fields: [{ key: "blood_pressure_sys", label: "Blood pressure — systolic", type: "number" }, { key: "blood_pressure_dia", label: "Blood pressure — diastolic", type: "number" }, { key: "heart_rate", label: "Heart rate (bpm)", type: "number" }, { key: "temperature", label: "Temperature (°C)", type: "number", step: "0.1" }, { key: "weight", label: "Weight (kg)", type: "number", step: "0.1" }, { key: "blood_sugar", label: "Blood sugar (mg/dL)", type: "number" }, { key: "spo2", label: "SpO₂ (%)", type: "number" }, { key: "notes", label: "Notes" }], getTitle: (record) => record.blood_pressure_sys || record.heart_rate ? "Vital-sign reading" : "Care reading", getDetail: (record) => [`BP ${record.blood_pressure_sys ?? "—"}/${record.blood_pressure_dia ?? "—"}`, record.heart_rate ? `Pulse ${record.heart_rate}` : null, record.spo2 ? `SpO₂ ${record.spo2}%` : null].filter(Boolean).join(" · ") },
};

function asRecord(value: unknown): RecordShape { return typeof value === "object" && value !== null ? value as RecordShape : {}; }
function defaultValues(resource: EditableResource): Record<string, string> { return Object.fromEntries(resources[resource].fields.map((field) => [field.key, field.key === "frequency" ? "Daily" : field.key === "time_of_day" ? "Morning" : ""])); }
function valuesFromRecord(resource: EditableResource, record: RecordShape): Record<string, string> { return Object.fromEntries(resources[resource].fields.map((field) => { const raw = record[field.key]; if (field.type === "datetime-local" && raw) { const date = new Date(String(raw)); return [field.key, Number.isNaN(date.getTime()) ? String(raw) : new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16)]; } return [field.key, raw == null ? "" : String(raw)]; })); }

function ConnectionRequired({ onConnect, label = "Connect your existing AgeCare account to load and save live care information." }: { onConnect: () => void; label?: string }) { return <section className="module-view"><div className="module-intro"><p className="eyebrow"><span className="reading-dot" /> Live AgeCare service</p><h2>Your care data stays private until you connect.</h2><p>{label}</p><Button className="primary-action" onClick={onConnect}>Connect AgeCare</Button></div><div className="module-stage"><span className="section-icon"><HeartHandshake size={20} /></span><h3>One secure connection, then the familiar services return.</h3><p>Use the email and password from the original AgeCare app. The connection is kept only in this browser.</p></div></section>; }

export function LiveCheckin({ connected, initialMood, isSaving, onConnect, onSave }: { connected: boolean; initialMood: number | null; isSaving: boolean; onConnect: () => void; onSave: (payload: CheckinPayload) => void }) {
  const [mood, setMood] = useState((initialMood ?? 2) + 1); const [energy, setEnergy] = useState(3); const [pain, setPain] = useState(0); const [sleepHours, setSleepHours] = useState<string>(""); const [notes, setNotes] = useState("");
  if (!connected) return <ConnectionRequired onConnect={onConnect} label="Sign in to save a daily check-in in the same AgeCare history used by the original application." />;
  function submit(event: FormEvent) { event.preventDefault(); onSave({ mood, energy, pain, sleepHours: sleepHours ? Number(sleepHours) : undefined, notes: notes.trim() || undefined }); }
  return <section className="live-module"><div className="live-module-head"><p className="eyebrow">A few moments for you</p><h2>Complete today’s check-in.</h2><p>Each answer is saved to your existing AgeCare care history.</p></div><form className="care-form" onSubmit={submit}><div className="form-question"><label>How does today feel?</label><div className="scale-buttons">{[1, 2, 3, 4, 5].map((value) => <button type="button" className={mood === value ? "is-selected" : ""} onClick={() => setMood(value)} key={value}>{value}</button>)}</div><small>1 is difficult; 5 feels bright.</small></div><div className="field-grid"><RangeField label="Energy" value={energy} min={1} max={5} onChange={setEnergy} /><RangeField label="Pain" value={pain} min={0} max={10} onChange={setPain} /></div><div className="field-grid"><label className="field-label">Sleep hours<input type="number" min="0" max="24" step="0.5" value={sleepHours} onChange={(event) => setSleepHours(event.target.value)} placeholder="Optional" /></label><label className="field-label">A note for your care record<textarea value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={1000} placeholder="Optional" /></label></div><div className="form-foot"><span><Check size={16} /> Saved to your AgeCare history</span><Button type="submit" className="ink-action" disabled={isSaving}>{isSaving ? <><LoaderCircle className="spin" size={17} /> Saving</> : "Save check-in"}</Button></div></form></section>;
}

function RangeField({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) { return <label className="range-field"><span>{label}<strong>{value}/{max}</strong></span><input type="range" min={min} max={max} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label>; }

export function HistoryModule({ connected, entries, loading, error, onConnect }: { connected: boolean; entries: unknown[]; loading: boolean; error?: string; onConnect: () => void }) { if (!connected) return <ConnectionRequired onConnect={onConnect} label="Sign in to view the check-ins you entered in the original AgeCare app." />; if (loading) return <LoadingPanel label="Loading your AgeCare history…" />; if (error) return <ServiceError message={error} />; return <section className="live-module"><div className="live-module-head"><p className="eyebrow">Your record over time</p><h2>Care history</h2><p>These entries are loaded from your existing AgeCare account.</p></div><div className="history-list">{entries.length === 0 ? <EmptyState icon={<ClipboardCheck size={22} />} title="Your care history is ready for its first entry." copy="Save a daily check-in and it will appear here." /> : entries.map((entry, index) => { const record = asRecord(entry); const date = record.created_at ? new Date(String(record.created_at)).toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }) : "Recorded check-in"; return <article className="history-entry" key={String(record.id ?? index)}><div className="history-date">{date}</div><div><div className="history-stats"><span>Mood <strong>{String(record.mood ?? "—")}/5</strong></span><span>Energy <strong>{String(record.energy ?? "—")}/5</strong></span><span>Pain <strong>{String(record.pain ?? "—")}/10</strong></span></div>{record.notes ? <p>{String(record.notes)}</p> : null}{record.ai_response ? <small className="ai-note">{String(record.ai_response)}</small> : null}</div></article>; })}</div></section>; }

export function FamilyModule({ connected, contacts, patients, loading, error, onConnect, onLink }: { connected: boolean; contacts: unknown[]; patients: unknown[]; loading: boolean; error?: string; onConnect: () => void; onLink: () => void }) { if (!connected) return <ConnectionRequired onConnect={onConnect} label="Sign in to view your AgeCare family contacts and linked patients." />; if (loading) return <LoadingPanel label="Loading your family circle…" />; if (error) return <ServiceError message={error} />; return <section className="live-module"><div className="live-module-head split-head"><div><p className="eyebrow">Shared with care</p><h2>Family circle</h2><p>Contacts and linked patients from your existing AgeCare account.</p></div><Button className="primary-action" onClick={onLink}><Link2 size={17} /> Link a patient</Button></div><div className="family-grid"><section><h3><UsersRound size={19} /> Family contacts</h3>{contacts.length === 0 ? <EmptyState icon={<UsersRound size={22} />} title="No family contacts yet." copy="Add contacts in the original AgeCare contact manager." /> : <div className="service-list">{contacts.map((item, index) => { const contact = asRecord(item); return <div key={String(contact.id ?? index)}><strong>{String(contact.name ?? "Family contact")}</strong><span>{String(contact.relationship ?? "Family")}</span><small>{String(contact.email ?? contact.phone ?? "No contact detail")}</small></div>; })}</div>}</section><section><h3><HeartHandshake size={19} /> Linked patients</h3>{patients.length === 0 ? <EmptyState icon={<HeartHandshake size={22} />} title="No patients linked yet." copy="Create a link by entering the patient’s registered email." /> : <div className="service-list">{patients.map((item, index) => { const patient = asRecord(item); return <div key={String(patient.id ?? index)}><strong>{String(patient.patient_name ?? patient.name ?? "Linked patient")}</strong><span>{String(patient.relationship ?? "Family")}</span><small>{String(patient.email ?? "")}</small></div>; })}</div>}</section></div></section>; }

export function LinkPatientModule({ connected, patients, isSaving, error, onConnect, onLink }: { connected: boolean; patients: unknown[]; isSaving: boolean; error?: string; onConnect: () => void; onLink: (email: string, relationship: string) => void }) { const [email, setEmail] = useState(""); const [relationship, setRelationship] = useState(""); if (!connected) return <ConnectionRequired onConnect={onConnect} label="Sign in to link a patient with your existing AgeCare account." />; function submit(event: FormEvent) { event.preventDefault(); onLink(email, relationship); setEmail(""); setRelationship(""); } return <section className="live-module"><div className="live-module-head"><p className="eyebrow">Connected care</p><h2>Link a patient.</h2><p>Use the email address from the patient’s registered AgeCare account.</p></div><form className="care-form link-form" onSubmit={submit}><label className="field-label">Patient’s registered email<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="patient@example.com" /></label><label className="field-label">Your relationship<input value={relationship} onChange={(event) => setRelationship(event.target.value)} placeholder="Daughter, son, caregiver…" /></label><div className="form-foot"><span><Check size={16} /> The patient must already be registered.</span><Button type="submit" className="ink-action" disabled={isSaving}>{isSaving ? <><LoaderCircle className="spin" size={17} /> Linking</> : "Link patient"}</Button></div></form>{error ? <ServiceError message={error} /> : null}<div className="linked-summary"><h3>Currently linked</h3>{patients.length === 0 ? <p>No patient links have been created in this account yet.</p> : patients.map((item, index) => { const patient = asRecord(item); return <p key={String(patient.id ?? index)}><strong>{String(patient.patient_name ?? patient.name ?? "Linked patient")}</strong> · {String(patient.relationship ?? "Family")}</p>; })}</div></section>; }

export function ResourceModule({ connected, resource, records, loading, error, saving, deleting, onConnect, onSave, onDelete }: { connected: boolean; resource: EditableResource; records: unknown[]; loading: boolean; error?: string; saving: boolean; deleting: boolean; onConnect: () => void; onSave: (resource: EditableResource, id: number | undefined, values: Record<string, string>) => Promise<boolean>; onDelete: (resource: EditableResource, id: number) => Promise<boolean> }) {
  const config = resources[resource]; const [editingId, setEditingId] = useState<number | undefined>(); const [formOpen, setFormOpen] = useState(false); const [values, setValues] = useState<Record<string, string>>(() => defaultValues(resource));
  if (!connected) return <ConnectionRequired onConnect={onConnect} label={`Sign in to load and manage ${config.title.toLowerCase()} from your existing AgeCare account.`} />; if (loading) return <LoadingPanel label={`Loading ${config.title.toLowerCase()}…`} />; if (error) return <ServiceError message={error} />;
  function beginCreate() { setEditingId(undefined); setValues(defaultValues(resource)); setFormOpen(true); }
  function beginEdit(record: RecordShape) { setEditingId(Number(record.id)); setValues(valuesFromRecord(resource, record)); setFormOpen(true); }
  async function submit(event: FormEvent) { event.preventDefault(); const saved = await onSave(resource, editingId, values); if (saved) { setFormOpen(false); setEditingId(undefined); setValues(defaultValues(resource)); } }
  async function remove(id: number) { if (window.confirm("Remove this record from AgeCare?")) await onDelete(resource, id); }
  return <section className="live-module"><div className="live-module-head split-head"><div><p className="eyebrow">{config.eyebrow}</p><h2>{config.title}</h2><p>{config.description}</p></div><Button className="primary-action" onClick={beginCreate}><Plus size={17} /> Add record</Button></div>{formOpen && <form className="care-form resource-form" onSubmit={submit}><div className="form-title"><strong>{editingId ? "Edit record" : `Add ${config.title.toLowerCase()}`}</strong><button type="button" className="icon-button" onClick={() => setFormOpen(false)} aria-label="Close record form"><X size={16} /></button></div><div className="field-grid">{config.fields.map((field) => <label className="field-label" key={field.key}>{field.label}{field.options ? <select value={values[field.key] ?? ""} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })}>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.required} type={field.type ?? "text"} step={field.step} value={values[field.key] ?? ""} onChange={(event) => setValues({ ...values, [field.key]: event.target.value })} />}</label>)}</div><div className="form-foot"><span><Check size={16} /> Updates save to your AgeCare account</span><Button type="submit" className="ink-action" disabled={saving}>{saving ? <><LoaderCircle className="spin" size={17} /> Saving</> : "Save record"}</Button></div></form>}<div className="resource-grid">{records.length === 0 ? <EmptyState icon={<CalendarDays size={22} />} title={config.emptyTitle} copy={config.emptyCopy} /> : records.map((item, index) => { const record = asRecord(item); const id = Number(record.id); return <article key={String(record.id ?? index)}><span className="section-icon"><Activity size={19} /></span><div className="record-card-copy"><strong>{config.getTitle(record)}</strong><p>{config.getDetail(record)}</p></div><div className="record-actions"><button type="button" aria-label="Edit record" onClick={() => beginEdit(record)}><Pencil size={15} /></button><button type="button" className="danger" aria-label="Delete record" onClick={() => remove(id)} disabled={deleting}><Trash2 size={15} /></button></div></article>; })}</div></section>;
}

export function ChatModule({ connected, messages, pending, onConnect, onSend }: { connected: boolean; messages: ChatMessage[]; pending: boolean; onConnect: () => void; onSend: (message: string) => void }) { const [message, setMessage] = useState(""); if (!connected) return <ConnectionRequired onConnect={onConnect} label="Sign in to use the care chat from your existing AgeCare account." />; function submit(event: FormEvent) { event.preventDefault(); const clean = message.trim(); if (!clean || pending) return; onSend(clean); setMessage(""); } return <section className="live-module chat-module"><div className="live-module-head"><p className="eyebrow">A gentle place to ask</p><h2>Care chat</h2><p>This conversation uses the original AgeCare service. It does not replace professional medical care.</p></div><div className="chat-thread">{messages.length === 0 ? <EmptyState icon={<MessageCircle size={22} />} title="Start with a question or a reflection." copy="You can ask about your wellbeing or organize a question for a care conversation." /> : messages.map((item, index) => <article className={`chat-bubble ${item.role}`} key={`${item.role}-${index}`}><span>{item.role === "user" ? "You" : "AgeCare assistant"}</span><p>{item.content}</p></article>)}{pending ? <div className="chat-thinking"><LoaderCircle className="spin" size={16} /> Thinking…</div> : null}</div><form className="chat-form" onSubmit={submit}><input value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Write a message…" maxLength={2000} /><Button type="submit" className="primary-action" disabled={pending || !message.trim()}><Send size={17} /> Send</Button></form></section>; }

export function LegacyLoginModal({ loading, onClose, onSubmit, onRegister, initialMode = "sign-in" }: { loading: boolean; onClose: () => void; onSubmit: (email: string, password: string) => void; onRegister: (fullName: string, email: string, password: string) => void; initialMode?: "sign-in" | "register" }) {
  const { t } = useLanguage();
  const [mode, setMode] = useState<"sign-in" | "register">(initialMode);
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmation, setConfirmation] = useState("");
  const [formError, setFormError] = useState("");
  const isRegistering = mode === "register";
  function changeMode(next: "sign-in" | "register") { setMode(next); setFormError(""); }
  function submit(event: FormEvent) {
    event.preventDefault();
    if (isRegistering) {
      const validationError = getRegistrationValidationError(password, confirmation);
      if (validationError) return setFormError(t(validationError));
      onRegister(fullName.trim(), email.trim(), password);
      return;
    }
    onSubmit(email.trim(), password);
  }
  return <div className="login-overlay" role="dialog" aria-modal="true" aria-labelledby="legacy-login-title"><form className="login-card" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose} aria-label={t("closeAccountAccess")}><X size={18} /></button><span className="section-icon"><HeartHandshake size={20} /></span><p className="eyebrow">{isRegistering ? t("newAccount") : t("existingAccount")}</p><h2 id="legacy-login-title">{isRegistering ? t("registerTitle") : t("connectTitle")}</h2><p>{isRegistering ? t("registerCopy") : t("signInCopy")}</p>{isRegistering && <label className="field-label">{t("fullName")}<input required minLength={2} value={fullName} onChange={(event) => setFullName(event.target.value)} autoComplete="name" /></label>}<label className="field-label">{t("email")}<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></label><label className="field-label">{t("password")}<input required minLength={isRegistering ? 6 : 1} type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={isRegistering ? "new-password" : "current-password"} /></label>{isRegistering && <label className="field-label">{t("confirmPassword")}<input required type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="new-password" /></label>}{formError && <p className="form-error" role="alert">{formError}</p>}<Button type="submit" className="primary-action login-submit" disabled={loading}>{loading ? <><LoaderCircle className="spin" size={17} /> {isRegistering ? t("creatingAccount") : t("connecting")}</> : isRegistering ? t("createAccount") : t("connectMyAccount")}</Button><button type="button" className="text-action auth-mode-button" onClick={() => changeMode(isRegistering ? "sign-in" : "register")}>{isRegistering ? t("alreadyHaveAccount") : t("newToAgeCare")}</button></form></div>;
}
function LoadingPanel({ label }: { label: string }) { return <section className="loading-panel"><LoaderCircle className="spin" size={23} /> {label}</section>; }
function ServiceError({ message }: { message: string }) { return <section className="service-error"><Activity size={20} /><div><strong>We could not load this service.</strong><p>{message}</p></div></section>; }
function EmptyState({ icon, title, copy }: { icon: ReactNode; title: string; copy: string }) { return <div className="empty-state"><span className="section-icon">{icon}</span><strong>{title}</strong><p>{copy}</p></div>; }
